config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/cities", to: 'cities#index'
  get '/', to: redirect('/cities')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  paginates_per 5

  scope :name_similar_to, ->(name) { where("name ilike ?", "%#{name}%") if name }
  scope :ordered_by, ->(order_by, desc=false) do 
    direction = desc ? :desc : :asc
    case order_by
      when "population"
        order(population: direction)
      when "name"
        order(name: direction)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  def index
    @cities = City.name_similar_to(params[:name])
                  .ordered_by(params[:order_by], params[:desc])
                  .page(params[:page])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper

  def search_placeholder()
    params[:name] || "City name(or part)"
  end
end

app/views/cities/index.html.erb
<h1> Table of Cities </h1>

<form class="form-inline" action="/cities" method="get">
  <div class="form-group mx-sm-3 mb-2">
     <%= text_field_tag "name", params[:name], placeholder: search_placeholder, class:"form-control" %> 
  </div>
  <button type="submit" class="btn btn-primary mb-2">Find</button>
</form>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">ID</th>

      <th scope="col">
        NAME 
        <div class="btn-group" role="group" aria-label="Basic example">
          <%= link_to "\u2b07", cities_path(name: params[:name], order_by: "name", desc: "true"), class: "btn btn-secondary btn-sm" %>
          <%= link_to "\u2b06", cities_path(name: params[:name], order_by: "name"), class: "btn btn-secondary btn-sm" %>
        </div>
      </th>

      <th scope="col">
        POPULATION
        <div class="btn-group" role="group" aria-label="Basic example">
          <%= link_to "\u2b07", cities_path(name: params[:name], order_by: "population", desc: "true"), class: "btn btn-secondary btn-sm" %>
          <%= link_to "\u2b06", cities_path(name: params[:name], order_by: "population"), class: "btn btn-secondary btn-sm" %>
        </div>
      </th>

    </tr>
  </thead>  
  <tbody>
    <% @cities.each do |c|%>
      <tr>
        <th scope="row"> <%= c.id %> </th>
        <td> <%= c.name %> </td>
        <td> <%= c.population %> </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @cities %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="/cities">
    <img src="city.png" width="30" height="30" class="d-inline-block align-top" alt="" loading="lazy">
    Cities
  </a>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CybercraftTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= favicon_link_tag "/city.png" %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  </head>

  <body>
    <%= render "layouts/header" %>
    <%=yield %>
  </body>
</html>